module.exports = {
  DIALOGFLOW_WEBHOOK_MESSENGER: process.env.DIALOGFLOW_WEBHOOK_MESSENGER,
  FACEBOOK_GRAPH_API_URL: process.env.FACEBOOK_GRAPH_API_URL,
  FACEBOOK_ACCESS_TOKEN: process.env.FACEBOOK_ACCESS_TOKEN,
  VERIFY_TOKEN: process.env.VERIFY_TOKEN
}
