module.exports = {
  DIALOGFLOW_WEBHOOK_MESSENGER: process.env.DIALOGFLOW_WEBHOOK_MESSENGER,
  // Facebook
  FACEBOOK_GRAPH_API_URL: process.env.FACEBOOK_GRAPH_API_URL,
  FACEBOOK_ACCESS_TOKEN: process.env.FACEBOOK_ACCESS_TOKEN,
  FACEBOOK_VERIFY_TOKEN: process.env.FACEBOOK_VERIFY_TOKEN,
  FACEBOOK_APP_SECRET: process.env.FACEBOOK_APP_SECRET,
  FACEBOOK_PLATFORM_ACCESS_TOKEN: process.env.FACEBOOK_PLATFORM_ACCESS_TOKEN,
  BOT_APP_ID: process.env.BOT_APP_ID,
  PLATFORM_APP_ID: process.env.PLATFORM_APP_ID
  // Google
  /* GOOGLE_PROJECT_ID: process.env.GOOGLE_PROJECT_ID,
  LANGUAGE_CODE: process.env.LANGUAGE_CODE,
  GOOGLE_CLIENT_EMAIL: process.env.GOOGLE_CLIENT_EMAIL,
  GOOGLE_PRIVATE_KEY: process.env.GOOGLE_PRIVATE_KEY */
}
